<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="5" time="0.105" timestamp="2021-07-06T10:59:34.263589" hostname="eero-thinkpad"><testcase classname="example_tests.test_example" name="test_passing_always" time="0.001" /><testcase classname="example_tests.test_example" name="test_failing_always" time="0.001"><failure message="assert False">&gt;   ???
E   assert False

/home/eero/Desktop/flaky-test-ci/tests/test_example.py:9: AssertionError</failure></testcase><testcase classname="example_tests.test_example" name="test_random_10percent_fail" time="0.000" /><testcase classname="example_tests.test_example" name="test_random_50percent_fail" time="0.000" /><testcase classname="example_tests.test_example" name="test_random_25percent_fail" time="0.000" /></testsuite></testsuites>